spring:
    profiles:
        active: ${environment}
    jackson:
        serialization:
            write-dates-as-timestamps: true
server:
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
